# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 177cb674dae6b7e3e2e461d47bac127293ec501120eb3e1b49418c7dde27b569db78c5c7e976b9884b2e0f2034224445c352079cd1072b33e6bb1ad12f48d51c

test:
  secret_key_base: f46c9d538a15031a4aabdc9edf79b38fd63e0264535353d088281091a0560dbcfcb4fcf49f9140cc86bebc5a60b42b93706cd30c0949ffe66d359e723a80f035

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
